In [22]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
import json

In [23]:
dataset = pd.read_csv('income_evaluation.csv')

In [24]:
dataset.head()

age          workclass   fnlwgt   education   education-num  \
0   39          State-gov    77516   Bachelors              13   
1   50   Self-emp-not-inc    83311   Bachelors              13   
2   38            Private   215646     HS-grad               9   
3   53            Private   234721        11th               7   
4   28            Private   338409   Bachelors              13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

    capital-gain   capital-loss   hours-per-week  native-country  income  
0           2174              0               40   United-States   <=50K  
1              0              0               13   United-States   <=50K  
2              0              0               40   United-States   <=50K  
3              0              0               40   United-States   <=50K  
4              0              0               40            Cuba   <=50K

In [25]:
len(dataset)

32561

In [34]:
df = pd.DataFrame() 
#df = dataset[['age', 'fnlwgt','education-num','capital-gain','capital-loss','hours-per-week','income']]
dataset.columns = list(map(lambda a: a.lstrip(), dataset.columns))
dataset.head()
#df = dataset.reindex(columns=['age', 'fnlwgt','education-num','capital-gain','capital-loss','hours-per-week','income'])
#df2 = dataset.income.map(dict(JSON.stringify('<=50K') = 1, JSON.stringify('>50K') =0))
dataset['income'].replace([' <=50K',' >50K'],[1,0], inplace=True)
df = dataset[['age', 'fnlwgt','education-num','capital-gain','capital-loss','hours-per-week','income']]

df.head(10)

age  fnlwgt  education-num  capital-gain  capital-loss  hours-per-week  \
0   39   77516             13          2174             0              40   
1   50   83311             13             0             0              13   
2   38  215646              9             0             0              40   
3   53  234721              7             0             0              40   
4   28  338409             13             0             0              40   
5   37  284582             14             0             0              40   
6   49  160187              5             0             0              16   
7   52  209642              9             0             0              45   
8   31   45781             14         14084             0              50   
9   42  159449             13          5178             0              40   

   income  
0       1  
1       1  
2       1  
3       1  
4       1  
5       1  
6       1  
7       0  
8       0  
9       0

In [35]:
#Finding out missing values in each column
print(df.isna().sum())
missing_status=df.isna().sum()

age               0
fnlwgt            0
education-num     0
capital-gain      0
capital-loss      0
hours-per-week    0
income            0
dtype: int64


In [36]:
# split dataset
X = df.iloc[:, :6] #take all rows & coulmns leaving the first column & last column(which will be the result) 
y = df.iloc[:, 6] #answer column
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0, test_size=0.3)

In [37]:
print(len(X_train))
print(len(y_train))
print(len(X_test))
print(len(y_test))

22792
22792
9769
9769


In [38]:
#Feature scaling
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [39]:
# KNN IMPLEMENTATION
import math
math.sqrt(len(y_test))

98.8382517044894

In [40]:
# Define the model: Init K-NN
classifier = KNeighborsClassifier(n_neighbors=97, p=2,metric='euclidean')

In [41]:
# Fit Model
classifier.fit(X_train, y_train)

KNeighborsClassifier(metric='euclidean', n_neighbors=97)

In [42]:
# Predict the test set results
y_pred = classifier.predict(X_test)
y_pred

array([1, 1, 1, ..., 0, 1, 1], dtype=int64)

In [43]:
# Evaluate Model
cm = confusion_matrix(y_test, y_pred)
print (cm)
print(f1_score(y_test, y_pred))

[[1002 1360]
 [ 369 7038]]
0.8906042391648213


In [44]:
print(accuracy_score(y_test, y_pred))

0.8230115672023749


In [45]:
# DECISION TREE IMPLEMENTATION

In [46]:
clf_entropy= DecisionTreeClassifier(criterion="entropy", random_state=0, max_depth=3, min_samples_leaf=5)
clf_entropy.fit(X_train,y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=3, min_samples_leaf=5,
                       random_state=0)

In [47]:
#function to make predictions
y_pred_en= clf_entropy.predict(X_test)
y_pred_en

array([1, 1, 1, ..., 0, 1, 1], dtype=int64)

In [48]:
print("Accuracy = ", accuracy_score(y_test,y_pred_en)*100)

Accuracy =  80.17197256628108


In [49]:
# RANDOM FOREST IMPLEMENTATION

In [50]:
random_model = RandomForestClassifier(n_estimators = 50, random_state = 30)

In [51]:
random_model.fit(X_train, y_train)

RandomForestClassifier(n_estimators=50, random_state=30)

In [52]:
prediction_test = random_model.predict(X_test)
prediction_test

array([1, 1, 1, ..., 0, 1, 1], dtype=int64)

In [53]:
from sklearn import metrics
print("Accuracy for random forrest = ", metrics.accuracy_score(y_test,prediction_test))

Accuracy for random forrest =  0.8019244549083837


In [54]:
print(f1_score(y_test, prediction_test))

0.872218186620881


In [55]:
print(random_model.feature_importances_ )

[0.20213976 0.37907291 0.12397421 0.14025821 0.05042512 0.10412978]
