In [79]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score

In [80]:
dataset = pd.read_csv('Loan Approval Dataset.csv')

In [81]:
len(dataset)
#dataset.head()

614

In [82]:
#len(dataset)
dataset.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [83]:
df = pd.DataFrame() 
df = dataset[['Dependents', 'ApplicantIncome','CoapplicantIncome','LoanAmount','Loan_Amount_Term','Credit_History']]
df2 = dataset.Loan_Status.map(dict(Y=1, N=0))
df['Loan_Status'] = df2
df.head(10)
df.tail(10)

C:\Users\parvi\AppData\Local\Temp/ipykernel_15964/3861171883.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Loan_Status'] = df2


Dependents  ApplicantIncome  CoapplicantIncome  LoanAmount  \
604          1            12000                0.0       496.0   
605          0             2400             3800.0         NaN   
606          1             3400             2500.0       173.0   
607          2             3987             1411.0       157.0   
608          0             3232             1950.0       108.0   
609          0             2900                0.0        71.0   
610         3+             4106                0.0        40.0   
611          1             8072              240.0       253.0   
612          2             7583                0.0       187.0   
613          0             4583                0.0       133.0   

     Loan_Amount_Term  Credit_History  Loan_Status  
604             360.0             1.0            1  
605             180.0             1.0            0  
606             360.0             1.0            1  
607             360.0             1.0            1  
608             360.0             1.0            1  
609             360.0             1.0            1  
610             180.0             1.0            1  
611             360.0             1.0            1  
612             360.0             1.0            1  
613             360.0             0.0            0

In [84]:
#Finding out missing values in each column
print(df.isna().sum())
missing_status=df.isna().sum()


Dependents           15
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Loan_Status           0
dtype: int64


In [85]:
##Replacing the missing data with 0 value
df = df.fillna(0)
print(df.head())

  Dependents  ApplicantIncome  CoapplicantIncome  LoanAmount  \
0          0             5849                0.0         0.0   
1          1             4583             1508.0       128.0   
2          0             3000                0.0        66.0   
3          0             2583             2358.0       120.0   
4          0             6000                0.0       141.0   

   Loan_Amount_Term  Credit_History  Loan_Status  
0             360.0             1.0            1  
1             360.0             1.0            0  
2             360.0             1.0            1  
3             360.0             1.0            1  
4             360.0             1.0            1  


In [86]:
print(df.isna().sum())

Dependents           0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Loan_Status          0
dtype: int64


In [87]:
df.Loan_Amount_Term.unique()
# should loan term amount contain 0 ??? (Ask doubt)
# assuming with the below definition : Loan amount term should not contain 0 values.
#When you take out a loan, you'll pay it back slowly over time through monthly payments. 
#At some point, you'll have repaid the entire loan and you'll be free of the debt. 
#The amount of time the lender gives you to repay your loan is called the term length, 
#or your “loan term"

array([360., 120., 240.,   0., 180.,  60., 300., 480.,  36.,  84.,  12.])

In [88]:
# Replace zeroes
#zero_not_accepted = ['Loan_Amount_Term']

#for column in zero_not_accepted:
  #  df1[column] = df1[column].replace(0, np.NaN)
   # mean = int(df1[column].mean(skipna=True))
   # df1[column] = df1[column].replace(np.NaN, mean)

In [89]:
# split dataset
X = df.iloc[:, 1:6] #take all rows & coulmns leaving the first column & last column(which will be the result) 
y = df.iloc[:, 6] #answer column
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0, test_size=0.2)

In [90]:
print(len(X_train))
print(len(y_train))
print(len(X_test))
print(len(y_test))

491
491
123
123


In [91]:
#Feature scaling
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [92]:
import math
math.sqrt(len(y_test))


11.090536506409418

In [93]:
# Define the model: Init K-NN
classifier = KNeighborsClassifier(n_neighbors=11, p=2,metric='euclidean')

In [94]:
# Fit Model
classifier.fit(X_train, y_train)

KNeighborsClassifier(metric='euclidean', n_neighbors=11)

In [95]:
# Predict the test set results
y_pred = classifier.predict(X_test)
y_pred

array([0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1], dtype=int64)

In [96]:
# Evaluate Model
cm = confusion_matrix(y_test, y_pred)
print (cm)
print(f1_score(y_test, y_pred))

[[15 18]
 [10 80]]
0.851063829787234


In [97]:
print(accuracy_score(y_test, y_pred))

0.7723577235772358
